layout_spectrum: 0.44455608003772795
typography_spectrum: 0.3657064863946289
color:
  brandColors:
    - '#ffffff'
    - '#4c4c4c'
    - '#000000'
    - '#fbaf41'
    - '#afafaf'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-56282977-1
  facebook: null
  twitter: null
name: UAV-Now
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Equipment
    id: 29f41908-dec8-4a6f-8f40-02a14bebeede
    type: content
  - name: FAQ
    id: 55744a09-14e2-40e6-9eb4-34b28a6785f8
    type: content
  - name: Contact Us
    id: 91f58c91-4f08-4004-b1a9-11dfce17063a
    type: content
favicon: null
title: UAV-Now    Aerial Photography Specialists
purpose: []
