name: UAV-Now
favicon: null
layout_spectrum: 0.29602
typography_spectrum: 0.48164
title: UAV-Now    Aerial Photography Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75223907-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4c4c'
    - '#000000'
    - '#fbaf41'
    - '#afafaf'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
