name: UAV-Now
favicon: null
layout_spectrum: 0.8908
typography_spectrum: 0.48164
title: UAV-Now    Aerial Photography Speacialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75223907-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4c4c'
    - '#000000'
    - '#fbaf41'
    - '#afafaf'
  brandStrength: 0.8125
  lightness: 0.12224204209633172
  saturation: 0.9965831185691059
  rhythmicContrast: 0.40764618990942836
purpose: []
