name: UAV-Now
favicon: null
layout_spectrum: 0.84116
typography_spectrum: 0.48164
title: UAV-Now    Aerial Photography Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-56282977-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4c4c'
    - '#000000'
    - '#fbaf41'
    - '#afafaf'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
